---
all:
  hosts:
    win-domain-controller:
      ansible_host: 192.168.1.100
      ansible_user: Administrator
      ansible_password: Password123
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
  children:
    domain_controllers:
      hosts:
        win-domain-controller:
    member_clients:
      hosts:
        win-client1:
          ansible_host: 192.168.1.101
          ansible_user: local_admin
          ansible_password: LocalPassword123
        win-client2:
          ansible_host: 192.168.1.102
          ansible_user: local_admin
          ansible_password: LocalPassword123