web1 ansible_host: server1.company.com ansible_connection=ssh ansible_user=root a$
web2 ansible_host: server2.company.com ansible_connection=ssh ansible_user=root a$
web3 ansible_host: server3.company.com ansible_connection=ssh ansible_user=root a$
db1 ansible_host: server4.company.com ansible_connection=winrm ansible_user=admin$

web_servers:
  web1: true
  web2: true
  web3: true

db_servers:
  db1: true

"all_servers:children":
  web_servers: true
  db_servers: true
