---
- name: Play 1
  hosts: localhost
  tasks:
    - name: Execute command 'date'
      #below is an ansible module
      command: date
    - name: Execute script on server
      #below is an ansible module
      script: test_script.sh

- name: Play 2
  hosts: localhost
  tasks:
    - name: Install web service
      #below is an ansible module
      yum:
        name: httpd
        state: present
    - name: Start web server
      #below is an ansible module
      service:
        name: httpd
        state: started
