---
- name: Add users
  microsoft.ad.computer:
    username: "{{ item.username }}"
    firstname: "{{ item.firstname }}"
    lastname: "{{ item.lastname }}"
    email: "{{ item.email }}"
    password: "{{ item.password }}"
    state: present
  loop: "{{ users }}"
